name: PostgreSQL Migration
on: workflow_dispatch
jobs:
  TestJob:
  runs-on: ubuntu-latest
  steps:
    -name: Download Liquibase
    -uses: actions/checkout@v2
    -uses: liquibase/liquibase-github-action@v4.23.2
