name: PostgreSQL Migration
on: workflow_dispatch
jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: set Java home
      run: |
        JAVA_CMD=""
        if [ -z ${JAVA_HOME+""} ];
        then
            echo "Using JAVA_HOME: $JAVA_HOME"
            JAVA_CMD=$JAVA_HOME/bin/java
        else
            echo "Using default java"
            JAVA_CMD=java
        fi

    - name: Download Liquibase
      run: |
        mkdir -p $HOME/liquibase
        cd $HOME/liquibase
        curl -o liquibase.zip -L https://github.com/liquibase/liquibase/archive/refs/tags/v4.23.0.zip --output liquibase.zip
        unzip -qq -o -d liquibase liquibase.zip
        chmod +x liquibase
        export PATH=$PATH:$HOME/liquibase
        java --version
        ./liquibase/liquibase -V
