name: PostgreSQL Migration
on: workflow_dispatch
jobs:
  TestJob:
    name: Install Liquibase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: liquibase/liquibase-github-action@v4.21.0
    - run: liquibase -V
